apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ilogger-system
spec:
  strategy:
    type: Recreate # Mantenemos esto para evitar bloqueos de disco en la Pi
  selector:
    matchLabels:
      app: ilogger-mongodb
  template:
    metadata:
      labels:
        app: ilogger-mongodb
    spec:
      securityContext:
        fsGroup: 999
      # --- ESTA ES LA SECCIÓN CLAVE ---
      initContainers:
      - name: fix-keyfile-permissions
        image: busybox
        # Copiamos la llave a un volumen compartido y le damos permisos 400 y dueño 999
        command: ["sh", "-c", "cp /tmp/raw-key/mongodb-keyfile /etc/mongo-key/mongodb-keyfile && chmod 400 /etc/mongo-key/mongodb-keyfile && chown 999:999 /etc/mongo-key/mongodb-keyfile"]
        volumeMounts:
        - name: raw-keyfile-volume
          mountPath: /tmp/raw-key
        - name: fixed-keyfile-volume
          mountPath: /etc/mongo-key
      # --------------------------------
      containers:
      - name: mongodb
        image: mongo:6.0
        args: 
          - "--bind_ip_all"
          - "--replSet"
          - "rs0"
          - "--keyFile"
          - "/etc/mongo-key/mongodb-keyfile" # Apuntamos al archivo corregido
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "ilogger_admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb-root-password
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
          subPath: mongodb-data
        # Montamos el volumen con la llave ya corregida
        - name: fixed-keyfile-volume
          mountPath: /etc/mongo-key
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-data-pvc
      # Volumen origen (el secreto de Kubernetes)
      - name: raw-keyfile-volume
        secret:
          secretName: mongodb-key-secret
      # Volumen destino (temporal en memoria para la llave corregida)
      - name: fixed-keyfile-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: ilogger-system
spec:
  ports:
  - port: 27017
  selector:
    app: ilogger-mongodb