---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secrets
  namespace: anami-masoterapia-prod
spec:
  encryptedData:
    password: AgBHoKXuCEudlTHevfhWe6kqenwKULYf1+bmvXGdtQsDEQ/3kWstkEyDnWEJMxoAlocIvQ4M3GrRBnMIBwv+n+3dWMxQH6kTpDy58K2a96Yaalk14umBil3WEHGl7KbeZ3uD1aOy2JJIdsEfG/hgNq5NNb2AVsMvDkpjwgPJr9c49270O1sme0fiXV33BM1g1E+8BHbR3OFs4k9cmeTIzKulsFYuCvx43e9MknousMBCC6vREmxf9R5NS8QI1J3PpDNGVj15KX2iE7/9GguUS4LnkXW+ENqosO+o7wYR2x5Cr+hLskaiONhWc0G4tZkJHMsPrKfcHsfeoScwtktUo5HYpyqSqNQI1p8SnymtEQ+q3CjlBb01wIijr30lOsJzvtl3YdaVRoWDr3waE+WED+sj08URq5CZ+ZTS1Jr+KeeiPWTQaGbjhEqkcFaRJQbdvYGAHxV792uabnWXbdI2OAKDiOO4Wg9OHSsmUuoXC3ZIArEdz8Lt3NFp6aFZqSPOPz8Ua9HnPBQdZZoAkbaTUNFl9PJE655CSpnjPW5ULWjMk22PUMCzafA57xIk9qMF5n9XWRgxtf7BjZgXNbGlTQTrwoyqxJ3RaoUmzxQ0s0ZFmljycE9whGancpufz9JuLjp9k6ld64OvyTHCvOPdtWQ+LFV+rpVClum8IIkpZW+mVMvvnAmbYUs0slfXZuOQlIQxM9jrlsnvEIRFrasX
    username: AgAHSbnjqWWFvFxodmGL6dpehfTg+O4+oFp7iYC53WraZ27/DUUqVH+KY2/3+1azr91C5Mnnmo8AytVmOg4gP7zPJjef1zSpUUrydRCmahtAO8ipiMiAnM/f/Vy7Tdku5mMFOMfaz8bFJepgPHwpgLlUQduw4W1W4MLM/T0ZGjO9z6F3ZPM7L0EB9UO93WykMtCT3Wj+SRcnGotGnt+rcQfrNwzDBC9K+mhC/EUxveDyF9Mm+yGtC8sJJflZqPwK+z/9ojLT13QRKPBBTSii//IMd0Pin19CLBNjH+1kPkrg+BsqZ0U081xdZ2y+0Y+SJO0XKw1xwIQNzGSa57rBkZnUHzrM1gS0//Pz5a15oo3eJg91Sl16dAH+BruTD4VjSXoDdU/3LmKpAVy76U9sd/e9PxwHtR+hMA36PPdGbb751lzIFnFXpXJTfKH7YxOsyESO+RGiGJ1kXeLLd0kOz6uQV5nn+oCI9wCmrOhHyFZPZi5hDmUHgelyc+KfkuH5e53u41e9eeTy2KnChZ6wG9IkdfzcIXPJU+9TjokYN2kqH1uEtyVC/aQDBtMriui77ez1ELM8Qom3TAdhdrh2n5W0zWumaOiRmLaYa1MXnCr+LVWgy4mUrzEnhGZ5skhxmIJ0JBCSqtgQVHtKGEGmKVmU45i8sxZWW8VoKnrFo0icixWLE9MtL/tB3riq6q3BrWwjjnJXlg==
  template:
    metadata:
      name: postgres-db-secrets
      namespace: anami-masoterapia-prod
