apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: anami-masoterapia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # Usamos el almacenamiento de Longhorn
  resources:
    requests:
      storage: 5Gi