apiVersion: apps/v1
kind: Deployment
metadata:
  name: anami-frontend
  namespace: anami-masoterapia-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anami-frontend
  template:
    metadata:
      labels:
        app: anami-frontend
    spec:
      containers:
      - name: frontend
        image: ikedaharket/anami-frontend:a9c1698
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: anami-frontend-svc
  namespace: anami-masoterapia-prod
spec:
  selector:
    app: anami-frontend
  ports:
  - port: 80
    targetPort: 80
