apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-local-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    # Indispensable: Dile a Traefik que el backend (Argo) usa HTTPS
    traefik.ingress.kubernetes.io/service.serversscheme: https
    # Indispensable: No verifiques el certificado (porque es auto-firmado)
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: argo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443