apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-local-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    # Las anotaciones deben tener dos espacios de sangría respecto a metadata
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: argocd-argocd-transport@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: argo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443 # Cambiado de 80 a 443