---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secrets
  namespace: anami-masoterapia-qa
spec:
  encryptedData:
    password: AgCi6EXAZn1eQUvpZOdSaKYALXNE6Du9qmOJ5xyAKtjJakeFwgwSHiUH0sT2SpL5Wfsdwk4HiXmMTYe3ARdy2f/+seAx0Kc1XEXuBl/LFIHormfP0BPzPZ5FpY0pYh/SVVwbo3Zdm/e8JlvAKeDfduFg9n895vjqAL4f9k6LF5w/os3cii3QRDySyyQg/Qx+SQbfPICxNMLBSUtNPO/qoTwF9m2+WBM11Ep+I9cCuLIhhs9VBX96lumdhZYuqGwj+Mpi2q3H49teSm53pxwlNqICQfRGzOc/I2YjDKTPQX8iTW9qXPr5yUf3bC3OlfaIowEWICOZX2umb6ZpeYmmRZKfXTgE+bHrSXviaLKz+k/IkRPMJbSIhHxobpJAETNnzSerOizPUM/bRd7kdoELzZ9IC8MPoHme7PBZOfr9qccVoRRS2KM4l7ghFkmkcbloAOgbyCKb+tnrGFnSLPAFtBKMs03Xhr2E5qZYBOKG/dYIAVA1jzl69SSz1QExtQ646bNdWww888J0isWRXv7yRpwwL4eG8WFPCuTKejh6Qg89blanBwxnUsNi8XwmrzMVUqZ7pEWQL3VvPj3tMTgwZx74yM93xyZL7XumMRzYPuib8cjqJ2NFIpxxwCNHhHUCgLFHvYZL8TQM9hB0mu0onLhcpIdAwfiWqPIxQjuOn0nm+MG7NdpCVIMWl7I4nNzwQaS+jDd8wzsyOjhbpk5A
    username: AgDP1JZZH5QUmsVaardJa7IqOa/VUlN56MY0/Z50Iz8GNaSmKq/X+QLVx8LmbqROd0uME1AJZUt+NfmmL8I+5UdcsUsDvJ+2m13r6WvIZNq22g2L8L00ohJgT2LviRk0D6l/xxmIknEGkAVCtEomE0ABkShdw4FjdlA1c94yiWkbs82KVLWakJGak0Je1tVDooILp+ZwSdwmw0+QM2PIO37jAN0nktShvg9M7AF3Rw7E2MqoXUajh5VdxdOUCr+h+679TNk6DzecYDw7/4u1WMXx7hlZfxh28KySZQy4tTXiSZPf+oHXiGrVPOrUCWh/jnh7Z2/l1NWMcDb/S0TJCTknaIKoIfcWAsqaOe1V9xub2AdHYYS+uVPqALzlTTd+r9QX5StOmfKjWwgSR2aVZsqva4MHACViMnkeezyOTE8h6loXwKo9um72o0LIPzc6oIN1EharBNX2ejy+XW0+FUYaDT4CUHLbcyBl65kV+0KdjpmG0YXs5d1JVrliXZkoX+zHQwjGeic5/X9b5v3OEdXpj1XGOOx8garoJ6+trOtSremTgWQH5Yrp72z78AaIMQ7jvyRSRoTr0+hW4356BPlHPWVamnGn1OXIJ1VY0VL2iMKDssNq439v6fJBBWlzaLRn5UyjGyovEpuRpzmIaMJy/faXuU3EO2uInRfKC5YQi6jzoMJmRhohXl9j7Ko1wwEh1ZDSxg==
  template:
    metadata:
      name: postgres-db-secrets
      namespace: anami-masoterapia-qa
