{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ilogger-api-secrets",
    "namespace": "ilogger-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ilogger-api-secrets",
        "namespace": "ilogger-system"
      }
    },
    "encryptedData": {
      "api-key": "AgDygBwsLIVs1DGkTUPnW/aJYZO9zDWT0leVw4qwQ55+O55jFn94BnspxDgPU73tTJC+IpanQlZUprT2zMJrBF22Wbmwq7dZMpyucUdYDII/N2Xos0jx8JEVbCwvzIC8OaEDzf+/4gXM+6mvXyHr6Z4D4ztkAQWZ7EFmT1zXAMl09wDz6SYtuV/Eg//5bJ+IdQ2FEjvhDxADk4BZVHfsvCoP1dIxEYFN+WpOd1R1g0xI0cnDX3H/srzDQBp981ZvgOXm3VrwLX5yKBae4g+eLO3s64bQQ4JneAXLKU8YpTfNp+Rx3P2+noKWFCySqG2qul9ZRmwB/ZCgITq70lFy6quqvyUNUzIXWCmWagqmBHEOtR39KbFTinMlMvbyL7BZJDEIbDVYuAc2HXAtzcGRBaV8dZMmvXp5M9TNwsf4j8dOXXFYLosg70+OXUsv9SqU1iRhAhrx3VHqaSabxLI35oa5SeEvKzr/AfPYMvH+3xItzpEXgGo2y1Ylk2YyMCvFzWboBwKYULs/ZUkQGzh80MzMh1+0v0ORTgqD/wx8qvmFGzi5PRyc9Xwqdi37Eeg9KjZ8PUr9n7TCbpV1KMlOg9dDoLyySIqGVzTRekDItAZBYE5TZ7mN2D1YNItfqPCyGMvGYWANFrasKaaXx+raYwnLDSUoUzLqPTWSVrZRbXYaTA47GQdeAwqWPGZ+W7pw1b1yjtpSSZP2NSz/DfnP",
      "mongo-uri": "AgBaABVjaABI/bzyQw0xMFtOLiNmDsX7ZN22k9dI8DodX8GrV8dYUoYHEG1FaRqxgO045nhHo/ltOB8SvBSP+kMp8cxIhawee42P9qdUV9AhCaskBP0WL7EeQytAFvyfx9Ag2RWATJ2BYOL2HcMHEK3aeHLWqQ/7OZrpuaMJZnRXG7BDsgek8n6+qAZORxGpN/l40E3lLfmH03ehgbEtgwk40KYTbgfYIgVUWMMY50Fl59o7rw2+bas2yyBS7TM3b4CMPX8/oS5QgeFQuoZTkLlIWbQB4f1ibUs2npKSzjKo+kp1fc6Hl0Gcm+kEXIL6nme41SaazfTY5I3oJGejQU2NgXbH2qLcD5TVmKC3uVmNTnMdYxRBFxkYvW1oAN/KA/JLoOcuD09ySiWFF+Oep11WGFkTi9kVJettJ89Y/GM1FV8PdDGGYQCv0RzVbdKrIkEizR3ZJzo3JQFRc1BqPy3mZp4Kw17tgUmuTN4oO4dAEE4lPh7Zws3jS20ZXK8OELL1vy8n8cBcTGrHLMczlaBeZ9/yEv0Qo8xHbEebYeFWPiETv4v7CrWf4IQ0wybpYVxr6SizQSURjN7gJLSW6BbfrMWwnU3YjQP8NyA+/91qDNUNkxVh9QX3QhsxbfYNbOo/AigycsLaOYVqQ7PRn6DHkoQ2LA+pGN8aXQExLcDdLkuuLiMnw80nv9tRAn6zrmYFk/miBgruJgtzCRmdemKgHW0Q8P0FjGpG4UlA/wTxLrdOlAS6134SXM110D8K4hBqKXZ+r3RGY8QlvUPr2ROtZBVwDl2RlStKhb3mIN8VpS8scwCtvumAGKECvi2eTAv09pNvVjznvc5giXBOzw=="
    }
  }
}
