apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilogger-api
  namespace: ilogger-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ilogger-api
  template:
    metadata:
      labels:
        app: ilogger-api
    spec:
      containers:
      - name: ilogger-api
        image: ikedaharket/ilogger:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ilogger-api-secrets
              key: mongo-uri
        - name: LOGGER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ilogger-api-secrets
              key: api-key
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"