apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilogger-api
  namespace: ilogger-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ilogger-api
  template:
    metadata:
      labels:
        app: ilogger-api # Etiqueta autorizada para hablar con Mongo
    spec:
      containers:
      - name: ilogger-api
        image: ikedadev/ilogger-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: ilogger-api-secrets # El secreto que generó Sealed Secrets
              key: mongo-uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: ilogger-api-svc
  namespace: ilogger-system
spec:
  selector:
    app: ilogger-api
  ports:
  - port: 80
    targetPort: 3000