---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secrets
  namespace: anami-masoterapia-prod
spec:
  encryptedData:
    password: AgDJrUXDJB4VK55e+2Q9J/IVhtrdEv6RagcCtPOjm09ImC53G72nYYGfOnRgHrZkZK2I/RefVdClvWdrJrOwqkwnbrHxVLx2WYvKRReyzLnc8k4ut4qE4KXhQz/2yVAQHkxNp7r1bv3TSY2gXrVQSWrBItoA8Z5wZ0FHZvk1MSC1VCsVs3lWQ8azp08+74czKlXmMaFkDZSNE9OBFoMI2j/ytJZ5Ji+f+2ErhuEQJYE+3Yzl+aK53FuFaysVF+dNneCDaoQLXfFA+HGPmkn1VspocGmq2jFUS6zFD4Lv5oNARMMHWmhdcbwNMgIEe/V85UJQwxMsoJi1ZLs8Yux6gRxym2OiLp1YDvuY3yhZG1rOUlM8PMKbAYYTio4BIrzIcohXXjHUOPKJuuWxIoIDE9soRnwkg29rB/a7VGLmFSLRrqmK25LTx6akwdC6AhwUUUj8IHtmdWB6wbR9WpL9pEAscPeyQ04EwG0P4eBk7o1pnB4TscBZpxTWiD+VsRkp/Cl9ExzDPLaPWCS0FzOLpOfbCDxeCt0tH+pEB3GznrIiWdMFFCP/xWu1wkseCFJVb8ya4EtAJzuJJc0viepnKyljXheZ/7vlOdjqaJ2I1uPwA23toDY+KQs3RvM5v/xNETdyr6e6QVfPSmKKSXFE8pJunyJwuB39cZM06tPYvB69omWv2jvA8zRACwZTjkzHM0b+xWDR4bureLBFj05p
    username: AgCCXLq66aPtF5OyJ9sv7XhXz2tQQF57jd0CUQ5vWv5fRvURkIG4s2xKF1UuRuJVfx5Um04gbH5x+6iPYepHlXCh6Xdn1CcPewziV9S+tMZT9Y8EkLwtd+Q8ZAF0Ag9GPzVcFeoymc0S7YWlRZOr1gnBzVduyUawaklF70fUxG0VVMqOPiUd8Y2q0HsQJYtowqddC5DNQb8gcNGD1oA73UIdTt441eCDRFTJrSt9uSWjENJzIivfbyEi4Fsjhn96ELnH4yscmTmyyKTcHFPIdxLXgDKzXTzbaOJehTgIpY6iPfPKH3coOS2S3Jg4rHP1RaPyW0e0MxrS/bBpXWAAgO6VvhMw7OsElpuek1yy1FHRZkO8Jdq31h/KO+XaYi1cf8/hCqxNVgqDsblo/ukzZGmYTu+Q7FpxAhoNSrW7hes3Vhr1f3eMaqveC08IdRSaU/fn4t43JOTwCZwgzg+/udhqZc2e/MnUKS3cJRdTCT9tEV4K/Tr69yCfvnPkd6Rz+N7QNsGZloJkJ+2VesF8dt+tYLDgHLy+nNJ7gy1Jf9zpSzIpE2UrMJ+GcGcCMkQdud7VQ3Ku4D2lVjUdSG2/9K0QFxrYCMe1cIrPUtBiAnxNEEDndEkrVMCC0g66Z+bZVed/Xkn0jCDYsnINpXsKB7kYSH3j33S33sIMM4S5PPKo5YqSGVOEkauIla4v/Udqw8JRTBQ6PA==
  template:
    metadata:
      name: postgres-db-secrets
      namespace: anami-masoterapia-prod
