---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-db-secrets
  namespace: anami-masoterapia
spec:
  encryptedData:
    password: AgBhfi66FZufyz+NsGXsWzaAr566c38bVdhIp98WZKTPcBbQibx43Pr3u8dDI/WAr5Jii2RiZDZqrf75N+iXsiVy1lvv8PSdy+OWMWylzWBw9S46/6lgHBM7VApH7wy9EpVdleqBg3VeWxqsx0dryHCNZ/y3eI7flGipa+PrIvdYIR6hU8G327QSXuBsf0OVEI9ck5nQhtN0aAyT3Azg0+8xKq5dxj3xYX0Uvfd+UYyWmggv7ZJNMdX668FtDz0Uc/jUL14VPwtSSuJwAMRtPoYLA6Sk3Oz8kiDJaBfNDR1qu6fQE5pYwCprg6e9cHj3naD6KzuIMZTiJw3OlS6gkaU6HK6Wo9vOLNUYKdN8349HYeSK9t9oDF9DJzKL+zofsXs0hZ3lx3OE6UHRsDl/HUkjC5a/kqBfgB29in169eWQ5MXhavozwNjHBmTlNWzkGpmNHlIFRfdObhRg3Ng3E5prE5XJqqTcjaCtRM1asKV4x5YYjj9/vgycTfDEvLtjAUCUpojmfG0LzJAZV8zFjx0m0EHQ0db5QKqzOC/Mn903rSsMJNqiBzm/mPARAa903T9BVEwMyaA2NN1rQG1949+c4vwciHzq2/FatRJlFWzz6ySni/QevSwTbM2vHGWUwqhHz5m4bZj9EQgUc4AcyBcmnPrWTu43DMNhr3Xf/ZDk3A0xQgOFP1on7RkKFCLnN+z0Ps6fbjpXTB7YIo49
    username: AgCn9b0BEMBbMhEAIYu7+vFGwxOs75NDMdIvLNKuHiBVTGviZR1dYd9LOzjoVm/Gg6+rBeGRrtSgh6MdCl79WN7eLOog+xItcVwprkw1U+m//LYVsVylyXGe0S3zT45o0023eFW6NJXS5QdiG/bFz8FE/TjLXpVqaagZFprakEPOMoIXs+RnxdWVxwBiYhMpLNjCfn8NqlSiQF5rhvCvVnDNsWnA2IoUykrgN110RWoUSnOupYIKklg+6RMRxP6ReC3RG5TaTGPLiNSbRlSWJvFXMXRawi4jq9o2YFiXclmNfJPLDO4I/O2FPSyGBgimyNwBaYT0m90X9ifG02J69khbI7+aQ0iaVTOdHeP3rLENQteUg+OAHMu4RyxUlAX6H9qIDBzobLcmuGMMBP9WL813avdTGvKqqbFo+CSahuxRf5gwu0b1L5LgpkOgZLK58JZFz17yXQhDNZi0cyYjQbBuYOAAKko8yB9QRCQk4a4FfnRs+nv1X5cPZKmhWJSerO5TcntbGTXWgF6/7pLYcMx59V+xvH3CJTxd58sRK+zWCGXtjmsrAeaEUoredPbsSaHPbriASIaZXMF80fhqX2B1AqEM9AC5OIZYYVR3fcR3diHMC3j5+HF01EjmdFNKW6eqSmmsrwx9sRDvpTMQFJCPuwM8+wlS0kYJ/lbyKDw9Hdcn5ysdbRwn/2quxJ2Jfv6FW5osJA==
  template:
    metadata:
      name: postgres-db-secrets
      namespace: anami-masoterapia
